pool:
  vmImage: 'ubuntu-16.04'
container: 'rust:latest'
steps:
  - script: cargo test --all
    displayName: Cargo test
  - script: cargo test --all --no-default-features
    displayName: Cargo test no features