[package]
name = "docket"
version = "0.1.7"
description = "Simple markdown to HTML documentation rendering"
readme = "README.md"
license-file = "LICENSE"
homepage = "https://iwillspeak.github.io/docket"
repository = "https://github.com/iwillspeak/docket"
authors = ["Will Speak <lithiumflame@gmail.com>"]

[dependencies]
pulldown-cmark = "0.1"
docopt = "0.8"
serde = "1.0"
serde_derive = "1.0"
log = "0.4"
env_logger = "0.4"
failure = "0.1"
notify = "4.0"